### ISSUE TITLE
Support more words?

### ISSUE THREAD

**Issue by BenEmdon** [Tuanhao/Japanese-Web-Game#1]
I am also trying to learn Japanese (so I can understand anime). This would be super great if you could one day grab more wordz somewhere from the internet❗️ 

Maybe could you also have all the words face up, and then have pictures on the bottom? That way when you match the pictures you match the words. (Just a suggestion tho)

![](https://media.giphy.com/media/anDhBXwgvIa7m/giphy.gif)

**Comment by Tuanhao** [comment]
Hi Ben, thank you for your interest. I am currently adding more words to the game. Still looking for an API that i can generate words. 
Are you talking about the thank you for playing picture? Making it to show in the bottom ??? 
"That way when you match the pictures you match the words." -> sorry i dont really get this sentence, can you ellaborate ?

**Comment by BenEmdon** [comment]
This is stale so Im closing this 🚫
